# Generated by Django 5.1.5 on 2025-02-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подписка (всплывающее окно)',
                'verbose_name_plural': 'Подписка (всплывающее окно)',
            },
        ),
    ]
