# Generated by Django 5.1.5 on 2025-02-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_newslettersubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersubscription',
            old_name='date_subscribed',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
