# Generated by Django 5.1.5 on 2025-07-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_socialnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterNavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название пункта меню')),
                ('url', models.CharField(max_length=255, verbose_name='URL или имя маршрута')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Пункт навигации футера',
                'verbose_name_plural': 'Пункты навигации футера',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InfoFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='footer_logo/', verbose_name='Логотип')),
                ('copyright', models.CharField(max_length=255, verbose_name='Копирайт')),
                ('phone', models.CharField(max_length=35, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('nav_items', models.ManyToManyField(blank=True, to='site_app.footernavitem', verbose_name='Пункты навигации')),
            ],
            options={
                'verbose_name': 'Инфофутер',
                'verbose_name_plural': 'Инфофутеры',
            },
        ),
    ]
