# Generated by Django 5.1.5 on 2025-02-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_sliderimage_link_sliderimage_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'verbose_name': 'Слайдер - Бренды', 'verbose_name_plural': 'Слайдер - Бренды'},
        ),
    ]
