# Generated by Django 5.1.5 on 2025-07-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_footernavitem_infofooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='infofooter',
            name='svg_icon',
            field=models.FileField(blank=True, null=True, upload_to='social_icons/svg/', verbose_name='SVG иконка'),
        ),
    ]
