# Generated by Django 5.1.5 on 2025-07-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_infofooter_svg_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofooter',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='footer_logo/', verbose_name='Логотип'),
        ),
    ]
