# Generated by Django 5.1.5 on 2025-03-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_alter_sliderimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='brand', max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands_logo_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Бренды',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.DeleteModel(
            name='SliderImage',
        ),
    ]
