# Generated by Django 5.1.5 on 2025-08-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_alter_infofooter_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Menu Name')),
                ('menu_item', models.CharField(max_length=100, verbose_name='Menu Item')),
                ('icon', models.CharField(max_length=10, verbose_name='Icon')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
            ],
        ),
    ]
