# Generated by Django 5.1.5 on 2025-03-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_brand_delete_sliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_id',
            field=models.IntegerField(default=0),
        ),
    ]
