# Generated by Django 5.1.5 on 2025-03-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0008_brand_brand_id'),
    ]

    operations = [
    ]
