# Generated by Django 5.1.5 on 2025-08-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0008_verticalmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalMenuName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя меню')),
            ],
        ),
        migrations.RemoveField(
            model_name='verticalmenu',
            name='menu_item',
        ),
    ]
