# Generated by Django 5.0.6 on 2024-05-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=100, verbose_name='Word')),
                ('word_gender', models.CharField(choices=[('Гоа', 'И что?'), ('Отлично', 'Неприлично'), ('Да', 'Нет')], max_length=7, verbose_name='Gender')),
            ],
        ),
    ]
