# Generated by Django 5.1.5 on 2025-04-09 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_photos/')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'стр.О нас',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('permission', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подписка (всплывающее окно)',
                'verbose_name_plural': 'Подписка (всплывающее окно)',
            },
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('step', models.CharField(blank=True, max_length=50, null=True)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=100, verbose_name='Word')),
                ('word_gender', models.CharField(choices=[('Отлично', 'Неприлично'), ('Да', 'Нет'), ('Гоа', 'И что?')], max_length=7, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_photos/')),
                ('description', models.CharField(default='Default description', max_length=255)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_images', to='bot_app.news')),
            ],
            options={
                'verbose_name': 'Изображение новости',
                'verbose_name_plural': 'Изображения новостей',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Название', max_length=300)),
                ('slug', models.SlugField(default='default-slug', max_length=300, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='photo')),
                ('desc', models.TextField(blank=True, default='Описание')),
                ('additional_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rating', models.CharField(blank=True, max_length=5, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('sizes', models.CharField(blank=True, max_length=100)),
                ('volume_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('material_up', models.CharField(blank=True, max_length=100)),
                ('power_source', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('show_quantity', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(blank=True, default=False, verbose_name='Популярные')),
                ('is_brand', models.BooleanField(blank=True, default=False, verbose_name='Имя Бренда')),
                ('is_index', models.BooleanField(blank=True, default=False, verbose_name='На главную')),
                ('is_site_bar', models.BooleanField(blank=True, default=False, verbose_name='В сайт Бар')),
                ('is_not_stock', models.BooleanField(blank=True, default=False, verbose_name='Нет в наличии')),
                ('is_sale', models.BooleanField(blank=True, default=False, verbose_name='Акции - Распродажи')),
                ('is_new_product', models.BooleanField(blank=True, default=False, verbose_name='Новинки')),
                ('is_main_slider', models.BooleanField(blank=True, default=False, verbose_name='В главный слайдер')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='site_app.brand')),
                ('category', models.ManyToManyField(related_name='products', to='site_app.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/additional/', verbose_name='Дополнительное изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='bot_app.product')),
            ],
            options={
                'verbose_name': 'ДопИзо Товара',
                'verbose_name_plural': 'ДопИзо Товара',
            },
        ),
    ]
