# Generated by Django 5.0.6 on 2024-06-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_alter_words_word_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Отлично', 'Неприлично'), ('Да', 'Нет'), ('Гоа', 'И что?')], max_length=7, verbose_name='Gender'),
        ),
    ]
