# Generated by Django 5.1.5 on 2025-06-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_alter_review_product_slug_alter_words_word_gender'),
        ('site_app', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_not_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_up',
        ),
        migrations.RemoveField(
            model_name='product',
            name='power_source',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume_liters',
        ),
        migrations.AddField(
            model_name='product',
            name='additives',
            field=models.TextField(blank=True, verbose_name='Добавки'),
        ),
        migrations.AddField(
            model_name='product',
            name='age_group',
            field=models.CharField(blank=True, max_length=50, verbose_name='Возрастная категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='application_area',
            field=models.CharField(blank=True, max_length=255, verbose_name='Область применения'),
        ),
        migrations.AddField(
            model_name='product',
            name='aroma',
            field=models.CharField(blank=True, max_length=100, verbose_name='Аромат'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Штрихкод'),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Емкость батареи (мАч)'),
        ),
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Калорийность (ккал)'),
        ),
        migrations.AddField(
            model_name='product',
            name='certification',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сертификаты'),
        ),
        migrations.AddField(
            model_name='product',
            name='clothing_fit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Посадка (Slim, Regular, Oversize)'),
        ),
        migrations.AddField(
            model_name='product',
            name='eco_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Экомаркировка'),
        ),
        migrations.AddField(
            model_name='product',
            name='effect',
            field=models.CharField(blank=True, max_length=255, verbose_name='Эффект (увлажнение, объем и т.п.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_efficiency',
            field=models.CharField(blank=True, max_length=50, verbose_name='Класс энергоэффективности'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип топлива'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, max_length=20, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='product',
            name='gluten_free',
            field=models.BooleanField(default=False, verbose_name='Без глютена'),
        ),
        migrations.AddField(
            model_name='product',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Вес брутто в кг', max_digits=7, null=True, verbose_name='Вес брутто'),
        ),
        migrations.AddField(
            model_name='product',
            name='hair_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип волос'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Высота в см', max_digits=6, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='horsepower',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Лошадиные силы'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='interface',
            field=models.CharField(blank=True, max_length=255, verbose_name='Интерфейсы (HDMI, USB и т.п.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_storage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Встроенная память'),
        ),
        migrations.AddField(
            model_name='product',
            name='launch_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода на рынок'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Длина в см', max_digits=6, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_volume',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Объем нетто в литрах', max_digits=7, null=True, verbose_name='Объем нетто'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional_value',
            field=models.TextField(blank=True, verbose_name='Пищевая ценность'),
        ),
        migrations.AddField(
            model_name='product',
            name='organic',
            field=models.BooleanField(default=False, verbose_name='Органический продукт'),
        ),
        migrations.AddField(
            model_name='product',
            name='power_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Потребляемая мощность (Вт)', max_digits=7, null=True, verbose_name='Потребление энергии'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, max_length=100, verbose_name='Разрешение экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='restock_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AddField(
            model_name='product',
            name='reusability',
            field=models.BooleanField(default=False, verbose_name='Многоразовое использование'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Диагональ экрана (дюймы)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=100, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип кожи'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Артикул (SKU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('out_of_stock', 'Нет в наличии'), ('preorder', 'Предзаказ'), ('discontinued', 'Снято с производства')], default='in_stock', max_length=20, verbose_name='Статус наличия'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, max_length=100, verbose_name='Стиль (лофт, модерн и т.п.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='site_app.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='product',
            name='torque',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Крутящий момент (Нм)'),
        ),
        migrations.AddField(
            model_name='product',
            name='transmission',
            field=models.CharField(blank=True, max_length=100, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(blank=True, max_length=100, verbose_name='Уникальный код товара (UPC)'),
        ),
        migrations.AddField(
            model_name='product',
            name='vegan',
            field=models.BooleanField(default=False, verbose_name='Веганский продукт'),
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle_compatibility',
            field=models.CharField(blank=True, max_length=255, verbose_name='Совместимость с авто'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period',
            field=models.PositiveIntegerField(blank=True, help_text='Гарантия в месяцах', null=True, verbose_name='Гарантия'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ширина в см', max_digits=6, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_description',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='site_app.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, default='Описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_quantity',
            field=models.BooleanField(default=False, verbose_name='Показывать количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размеры (S, M, L и т.п.)'),
        ),
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Гоа', 'И что?'), ('Да', 'Нет'), ('Отлично', 'Неприлично')], max_length=7, verbose_name='Gender'),
        ),
    ]
