# Generated by Django 5.1.5 on 2025-06-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_remove_product_capacity_remove_product_is_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Да', 'Нет'), ('Отлично', 'Неприлично'), ('Гоа', 'И что?')], max_length=7, verbose_name='Gender'),
        ),
    ]
