# Generated by Django 5.1.5 on 2025-06-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0006_alter_words_word_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Да', 'Нет'), ('Гоа', 'И что?'), ('Отлично', 'Неприлично')], max_length=7, verbose_name='Gender'),
        ),
    ]
