# Generated by Django 5.1.5 on 2025-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_alter_words_word_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ёмкость/вместимость', max_digits=10, null=True, verbose_name='Ёмкость'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_up',
            field=models.CharField(blank=True, max_length=100, verbose_name='Материал (верхний слой)'),
        ),
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Отлично', 'Неприлично'), ('Да', 'Нет'), ('Гоа', 'И что?')], max_length=7, verbose_name='Gender'),
        ),
    ]
