# Generated by Django 5.0.6 on 2024-12-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_product_alter_words_word_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Гоа', 'И что?'), ('Да', 'Нет'), ('Отлично', 'Неприлично')], max_length=7, verbose_name='Gender'),
        ),
    ]
