# Generated by Django 5.1.5 on 2025-06-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_product_capacity_product_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, default='Название', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Гоа', 'И что?'), ('Отлично', 'Неприлично'), ('Да', 'Нет')], max_length=7, verbose_name='Gender'),
        ),
    ]
