# Generated by Django 5.1.5 on 2025-06-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0009_alter_product_name_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Артикул (SKU)'),
        ),
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Гоа', 'И что?'), ('Да', 'Нет'), ('Отлично', 'Неприлично')], max_length=7, verbose_name='Gender'),
        ),
    ]
