# Generated by Django 5.1.5 on 2025-06-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0010_alter_product_sku_alter_words_word_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aroma',
            field=models.CharField(blank=True, max_length=300, verbose_name='Аромат'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=300, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ёмкость/вместимость', max_digits=100, null=True, verbose_name='Ёмкость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=150, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='engine_type',
            field=models.CharField(blank=True, max_length=300, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=300, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_type',
            field=models.CharField(blank=True, max_length=300, verbose_name='Тип волос'),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_storage',
            field=models.CharField(blank=True, max_length=300, verbose_name='Встроенная память'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=300, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_up',
            field=models.CharField(blank=True, max_length=300, verbose_name='Материал (верхний слой)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=300, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, max_length=300, verbose_name='Разрешение экрана'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=300, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_type',
            field=models.CharField(blank=True, max_length=300, verbose_name='Тип кожи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, max_length=300, verbose_name='Стиль (лофт, модерн и т.п.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='transmission',
            field=models.CharField(blank=True, max_length=300, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.CharField(blank=True, max_length=300, verbose_name='Уникальный код товара (UPC)'),
        ),
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Гоа', 'И что?'), ('Отлично', 'Неприлично'), ('Да', 'Нет')], max_length=7, verbose_name='Gender'),
        ),
    ]
