# Generated by Django 5.0.6 on 2024-12-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0011_alter_words_word_gender_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
