# Generated by Django 5.1.5 on 2025-06-22 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0012_alter_words_word_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Отлично', 'Неприлично'), ('Гоа', 'И что?'), ('Да', 'Нет')], max_length=7, verbose_name='Gender'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Артикул вариации')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Размер')),
                ('color', models.CharField(blank=True, max_length=150, verbose_name='Цвет')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена вариации')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='Изображение вариации')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='bot_app.product', verbose_name='Основной товар')),
            ],
            options={
                'verbose_name': 'Вариация товара',
                'verbose_name_plural': 'Вариации товара',
            },
        ),
    ]
