# Generated by Django 5.0.6 on 2024-12-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0012_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='show_quantity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Да', 'Нет'), ('Гоа', 'И что?'), ('Отлично', 'Неприлично')], max_length=7, verbose_name='Gender'),
        ),
    ]
