# Generated by Django 5.0.6 on 2024-12-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0014_alter_product_show_quantity_alter_words_word_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='show_quantity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Да', 'Нет'), ('Отлично', 'Неприлично'), ('Гоа', 'И что?')], max_length=7, verbose_name='Gender'),
        ),
    ]
