# Generated by Django 5.1.5 on 2025-06-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0014_productvariant_description_alter_words_word_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True, verbose_name='Цена вариации'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размер'),
        ),
    ]
