# Generated by Django 5.1.5 on 2025-08-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0023_userprofile_location_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Гоа', 'И что?'), ('Да', 'Нет'), ('Отлично', 'Неприлично')], max_length=7, verbose_name='Gender'),
        ),
    ]
