# Generated by Django 5.1.5 on 2025-02-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0024_alter_news_options_alter_newsimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
