# Generated by Django 5.1.5 on 2025-08-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0024_alter_words_word_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Да', 'Нет'), ('Отлично', 'Неприлично'), ('Гоа', 'И что?')], max_length=7, verbose_name='Gender'),
        ),
    ]
