# Generated by Django 5.1.5 on 2025-02-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0037_alter_words_word_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Отлично', 'Неприлично'), ('Гоа', 'И что?'), ('Да', 'Нет')], max_length=7, verbose_name='Gender'),
        ),
    ]
