# Generated by Django 5.1.5 on 2025-03-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0039_alter_words_word_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='photo'),
        ),
    ]
