# Generated by Django 5.1.5 on 2025-03-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0040_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Гоа', 'И что?'), ('Да', 'Нет'), ('Отлично', 'Неприлично')], max_length=7, verbose_name='Gender'),
        ),
    ]
