# Generated by Django 5.1.5 on 2025-03-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0041_alter_words_word_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Отлично', 'Неприлично'), ('Да', 'Нет'), ('Гоа', 'И что?')], max_length=7, verbose_name='Gender'),
        ),
    ]
