# Generated by Django 5.1.5 on 2025-03-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0047_alter_product_additional_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, default='Название', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Отлично', 'Неприлично'), ('Да', 'Нет'), ('Гоа', 'И что?')], max_length=7, verbose_name='Gender'),
        ),
    ]
