# Generated by Django 5.1.5 on 2025-03-04 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0048_alter_product_name_alter_product_slug_and_more'),
        ('site_app', '0007_brand_delete_sliderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='site_app.brand'),
        ),
        migrations.AlterField(
            model_name='words',
            name='word_gender',
            field=models.CharField(choices=[('Отлично', 'Неприлично'), ('Гоа', 'И что?'), ('Да', 'Нет')], max_length=7, verbose_name='Gender'),
        ),
    ]
